### ISSUE TITLE
Change UUID for Vectrail

### ISSUE THREAD

**Issue by 12rcu** [TimoliaDE/HowTo#106]
Account change, no access to old account:
old uuid: `b21f4cbc-9b2e-4099-8abd-9d794ee75432`
new uuid: `464cf9e6-6be8-49df-b63d-0c44482cd53c`

**Comment by l3nnartt** [comment]
done with https://github.com/TimoliaDE/HowTo/commit/97eb97192c662be483972550124deb772c6157e9
