### ISSUE TITLE
Unban requests to HowTo

### ISSUE THREAD

**Issue by l3nnartt** [TimoliaDE/HowTo#11]
Information on the unban requests must be added in the Howto
https://forum.timolia.de/threads/einen-entbannungsantrag-schreiben.21927/#post-77036

**Comment by Schneeeulen** [comment]
https://howto.timolia.de/bans/

Der Forum Artikel ist unereichbar, aber genügen diese Informationen?

**Comment by l3nnartt** [comment]
Ja, denke das passt.
Wichtig war halt dass irgendwo steht auf dem Discord melden da es das Forum nicht mehr gibt.
