### ISSUE TITLE
LabyMod Cashback infos

### ISSUE THREAD

**Issue by l3nnartt** [TimoliaDE/HowTo#12]
some people don't know what the labymod cashback is, a short explanation and a table of how many coins you get at which rank

**Comment by Schneeeulen** [comment]
"Timolia ist ofizieller LabyMod Partner. Mit dem Kauf eines Premium-Ranges auf unserem Netzwerk erhälst du LabyMod Coins mit welchen du Cosmetics, Emotes und vieles mehr im LabyMod Shop erwerben kannst."

Hast du dir sowas vorgestellt?

**Comment by l3nnartt** [comment]
ja, und nach Möglichkeit wäre noch eine Tabelle gut mit welchem Rang man welches Cashback kriegt.
Durch die Umstellung auf monatliche Ränge fällt das wohl aber weg und es gibt das nur noch durch Pixelbooster

**Comment by l3nnartt** [comment]
added cashback info:
https://github.com/TimoliaDE/HowTo/pull/56
