### ISSUE TITLE
xlinx → Management des Sup Teams (-Dev-)

### ISSUE THREAD

**Issue by xlinx01** [TimoliaDE/HowTo#61]

**Comment by Schneeeulen** [comment]
Okay, das ist irgendwie blöd gelaufen, du hast hier auf eine Antwort gewartet, und ich in #HowTo auf dem DC. 
Jedenfalls ist es im Master Richtig, @l3nnartt ist das ein Updatefehler?

**Comment by l3nnartt** [comment]
ja, steht auch bei ihr seit dem Commit hier
https://github.com/TimoliaDE/HowTo/commit/854197b2b899debe4b37b0a0322b47da141e1c7f

War nur im Code etwas was angepasst werden musste, das hab ich hier gemacht
https://github.com/TimoliaDE/HowTo/commit/2b043e114a97c9ad1142af8e295d8b8430b70c3b
