### ISSUE TITLE
JumpWorld Import to FAQ

### ISSUE THREAD

**Issue by l3nnartt** [TimoliaDE/HowTo#7]
It would be good if the JumpWorld import is explained in the FAQ to make it as easy as possible for old/new people to bring their old maps back into JumpWorld

**Comment by Schneeeulen** [comment]
Wie sieht eigentlich der Status damit aus @l3nnartt Denn im Moment sind generell keine Imports möglich. Ist das dauerhaft?

**Comment by l3nnartt** [comment]
Man hatte ja 2 Jahre lang Zeit, dadurch dass die 1.8 Server nicht mehr gestartet werden können ist das vorerst ein dauerhafter Zustand bis man sich die Mühe macht anzuschauen dass die Welten auch auf einem 1.20+ Server geladen werden können.

**Comment by l3nnartt** [comment]
Imports no longer possible, info added in faq
https://github.com/TimoliaDE/HowTo/pull/56
