### ISSUE TITLE
Import Text from JumpWorld Browser

### ISSUE THREAD

**Issue by l3nnartt** [TimoliaDE/HowTo#8]
The texts and explanations from the [JumpWorld Browser](https://jumpworld.timolia.de/) should also be available in German and English in the HowTo

**Comment by Schneeeulen** [comment]
Auf dieser Webseite hast du die Möglichkeit, nach JnRs zu suchen, ihre Topzeiten und Bewertungen einzusehen und, solltest du auch ingame online sein, durch anklicken des "Beitreten"-Buttons direkt in das JnR joinen.

Das ist die Überschrift des Browsers, kopiert ins HowTo

**Comment by Schneeeulen** [comment]
im Englischen hat es komplett gefehlt. Das habe ich ergänzt
